colName = input('Please enter the college name: ')
disc= input('Which discipline please? ')
dayType = input('Is it open day or orientation day? ')
whatDay = input('What day? (dd/mm/yyyy): ')
sttTime = input('What start time (hh:mm)? ')
amPm = input('Is it am or pm? ')
whatCampus = input('What campus? ')
room = input('What room? ')
print(f'Welcome to Victoria University, {colName}({disc}) {dayType} Day!')
print(f'The date is {whatDay}.\nThe time is {sttTime}{amPm}.\nLocation: Room {room}, {whatCampus} Campus!')
