ing1 = input('Ingredient 1: ')
qty1 = int(input('Quantity for ingredient 1: '))
ing2 = input('Ingredient 2: ')
qty2 = int(input('Quantity for ingredient 2: '))
ing3 = input('Ingredient 3: ')
qty3 = int(input('Quantity for ingredient 3: '))
ing4 = input('Ingredient 4: ')
qty4 = int(input('Quantity for ingredient 4: '))
print(f'{ing1} {qty1}g')
print(f'{ing2} {qty2}kg')
print(f'{ing3} {qty3}g')
print(f'{ing4} {qty4} tin')
