collegeName = input("Please enter the college name: ")
discipline = input("Which discipline please? ")
openDay = input("Is it open day or Orientation Day? ")
whatDay = input("What day? (dd/mm/yyyy) ")
startTime = input("What start time? (hh:mm) ")
pmAm = input("Is it PM or AM? ")
campus = input("What campus? ")
room = input("What room? ")
print(f'Welcome to Victoria University, {collegeName}({discipline}) {openDay} Day!')
print(f'The date is {whatDay}')
print(f'The time is {startTime}{pmAm}')
print(f'Location: Room {room}, {campus} campus.')
